version: 0.0
os: linux

files:
  - source: /
    destination: /opt/codedeploy/

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
