name: Build a WAR file using Maven

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: scaler
    steps:
    - uses: actions/checkout@v3
    - name: kubernetes deploy
      run: kubectl run scalerpod --image=vilasvarghese/test
